apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: acme@ldaws.com
    privateKeySecretRef:
      name: lets-encrypt-acme-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: lets-encrypt-cloudflare-api-token
              key: api-token
