---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: cluster-ingress-nginx

---

apiVersion: v1
kind: Namespace
metadata:
  name: cygnus
  labels:
    app.kubernetes.io/name: cygnus

---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/instance: bulk-storage
