apiVersion: apps/v1
kind: Deployment
metadata:
  name: monicahq
  labels:
    app.kubernetes.io/name: monicahq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: monicahq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monicahq
    spec:
      containers:
      - name: app
        image: docker.io/monicahq/monicahq
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        envFrom:
          - configMapRef:
              name: monica-app-env
              optional: false
          - secretRef:
              name: monica-app-secrets
              optional: false
        volumeMounts:
        - name: monicahq-data
          mountPath: /var/www/monica/storage
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi

      volumes:
        - name: monicahq-data
          persistentVolumeClaim:
            claimName: monicahq-data
