apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monicahq-assets
spec:
  storageClassName: cygnus-state
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
