apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ExternalName
  externalName: swan.home.ldaws.net

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ExternalName
  externalName: swan.home.ldaws.net
