# https://github.com/stefanprodan/podinfo/blob/4.0.6/kustomize/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app.kubernetes.io/name: mailhog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mailhog
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: smtp
      port: 25
      protocol: TCP
      targetPort: smtp
