kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/instance: monicahq

resources:
- ../../../bases/monicahq
- ingress.yaml

configMapGenerator:
  - name: monica-app-env
    behavior: merge
    literals:
      - "APP_DEBUG=true"

secretGenerator:
  - name: monica-app-secrets
    behavior: replace
    type: opaque
    envs:
      - secret/.env
