apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-admission
  labels:
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
  selector:
    app.kubernetes.io/component: controller
