commonLabels:
  app.kubernetes.io/name: traefik
  app.kubernetes.io/instance: traefik-ingress

namespace: traefik-ingress

resources:
  - ./clusterrole.yaml
  - ./clusterrole-binding.yaml
  - ./serviceaccount.yaml
  - ./daemonset.yaml
  - ./service.yaml
