apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  labels:
    app.kubernetes.io/component: traefik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: traefik
  ports:
    # if you change the ports, check the patches
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
    - port: 443
      name: https
      targetPort: https
      protocol: TCP
