kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  com.ldaws.lab/env: Production
  com.ldaws.lab/cluster: cygnus

commonAnnotations:
  com.ldaws.lab/cluster-component: infrastructure

resources:
  # - namespaces.yaml
  # - storageclasses.yaml
  # - metallb/
  # - ../bases/ingress-nginx
  - cert-manager/
  # - state/
